version: "3.9"

services:
  proxy:
    image: 999k923/docker-proxy:latest
    container_name: proxy-server
    restart: unless-stopped
    environment:
      SERVICE_TYPE: 1  # 1: hy2, 2: tuic
    ports:
      - "28888:28888/tcp"
      - "28888:28888/udp"
    volumes:
      - ./proxy_files:/proxy_files  # 可选：挂载配置/证书持久化
