services:
  proxy:
    image: 999k923/docker-proxy:latest
    container_name: proxy_server
    restart: always
    network_mode: host        # host 网络模式保证 UDP/IPv6 正常
    environment:
      SERVICE_TYPE: 1         # 1=hy2, 2=tuic
    volumes:
      - /opt/stacks/proxy_server/data:/proxy_files
